[package]
name = "r-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
r-lexer = { path = "../r-lexer" }
r-source = { path = "../r-source" }
r-syntax = { path = "../r-syntax" }
rowan.workspace = true

[lints]
workspace = true
